'use client'
import { useMemo, useState } from 'react'

type Provedor = 'herdar' | 'automatico' | 'anthropic' | 'openai' | 'desativado'
export type GlobalIA = { provedor: Exclude<Provedor, 'herdar'>; modelo: string; limiteRequisicoes: number; limiteTokens: number; maxTokensResposta: number; timeoutSegundos: number; fallbackAutomatico: boolean }
export type EmpresaIA = { empresaId: string; empresaNome: string; habilitado: boolean; provedor: Provedor; modelo: string; limiteRequisicoesMes: number; limiteTokensMes: number; maxTokensResposta: number; fallbackAutomatico: boolean; uso: { requisicoes: number; tokens: number; tokensEntrada: number; tokensSaida: number; erros: number } }
type StatusProvedor = { configurado: boolean; origem: string }
const modelos: Record<Provedor, { valor: string; nome: string }[]> = {
  herdar: [{ valor: '', nome: 'Usar padrão da plataforma' }], automatico: [{ valor: '', nome: 'Regras e cálculos do sistema' }], desativado: [{ valor: '', nome: 'Sem IA' }],
  anthropic: [{ valor: 'claude-haiku-4-5-20251001', nome: 'Claude Haiku — econômico' }, { valor: 'claude-sonnet-5', nome: 'Claude Sonnet — avançado' }],
  openai: [{ valor: 'gpt-5.6-luna', nome: 'GPT-5.6 Luna — econômico' }, { valor: 'gpt-5.6-terra', nome: 'GPT-5.6 Terra — equilibrado' }, { valor: 'gpt-5.6-sol', nome: 'GPT-5.6 Sol — avançado' }],
}
const nomes: Record<Provedor, string> = { herdar: 'Padrão da plataforma', automatico: 'Automático', anthropic: 'Anthropic', openai: 'OpenAI', desativado: 'Desativado' }
const fmt = (n: number) => n.toLocaleString('pt-BR')

export default function IAAdminClient({ empresas: iniciais, globalInicial, provedores, schemaDisponivel }: { empresas: EmpresaIA[]; globalInicial: GlobalIA; provedores: { anthropic: StatusProvedor; openai: StatusProvedor }; schemaDisponivel: boolean }) {
  const [empresas, setEmpresas] = useState(iniciais), [global, setGlobal] = useState(globalInicial), [globalEdit, setGlobalEdit] = useState(globalInicial)
  const [busca, setBusca] = useState(''), [editando, setEditando] = useState<EmpresaIA | null>(null), [salvando, setSalvando] = useState(false), [mensagem, setMensagem] = useState('')
  const filtradas = useMemo(() => empresas.filter(e => e.empresaNome.toLowerCase().includes(busca.toLowerCase())), [empresas, busca])
  const total = empresas.reduce((a, e) => ({ req: a.req + e.uso.requisicoes, tokens: a.tokens + e.uso.tokens, entrada: a.entrada + e.uso.tokensEntrada, saida: a.saida + e.uso.tokensSaida, erros: a.erros + e.uso.erros }), { req: 0, tokens: 0, entrada: 0, saida: 0, erros: 0 })
  const alteraEmpresa = <K extends keyof EmpresaIA>(k: K, v: EmpresaIA[K]) => setEditando(a => a ? { ...a, [k]: v } : null)
  const alteraGlobal = <K extends keyof GlobalIA>(k: K, v: GlobalIA[K]) => setGlobalEdit(a => ({ ...a, [k]: v }))
  async function enviar(body: Record<string, unknown>) { const r = await fetch('/api/saas-admin/ia/config', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const d = await r.json(); if (!r.ok || !d.ok) throw new Error(d.erro ?? 'Não foi possível salvar.') }
  async function salvarGlobal() { setSalvando(true); setMensagem(''); try { await enviar({ escopo: 'global', ...globalEdit }); setGlobal(globalEdit); setMensagem('Política padrão atualizada.') } catch (e) { setMensagem(e instanceof Error ? e.message : 'Erro ao salvar.') } finally { setSalvando(false) } }
  async function salvarEmpresa() { if (!editando) return; setSalvando(true); setMensagem(''); try { await enviar({ escopo: 'empresa', ...editando }); setEmpresas(l => l.map(i => i.empresaId === editando.empresaId ? editando : i)); setMensagem('Política do cliente atualizada.') } catch (e) { setMensagem(e instanceof Error ? e.message : 'Erro ao salvar.') } finally { setSalvando(false) } }
  return <div className="space-y-7">
    <div className="flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-indigo-400">Governança da plataforma</p><h1 className="mt-1 text-2xl font-bold text-white">IA e Consumo</h1><p className="mt-1 text-sm text-slate-400">Provedores, modelos, limites e rastreabilidade por cliente.</p></div><span className="rounded-full border border-emerald-800 bg-emerald-950/50 px-3 py-1.5 text-xs text-emerald-300">Segredos protegidos no servidor</span></div>
    {!schemaDisponivel && <div className="rounded-xl border border-amber-800 bg-amber-950/40 p-4 text-sm text-amber-300"><strong>Migração pendente.</strong> Esta é uma prévia segura; o sistema permanece no modo anterior.</div>}
    <section><Titulo titulo="Provedores da plataforma" descricao="A tela mostra disponibilidade, mas nunca revela uma chave." /><div className="mt-3 grid gap-4 lg:grid-cols-3"><Provider nome="Anthropic" detalhe="Claude · análise e conteúdo" status={provedores.anthropic} /><Provider nome="OpenAI" detalhe="GPT · análise executiva" status={provedores.openai} /><div className="card-ia"><div className="flex justify-between"><div><p className="font-semibold text-white">Motor automático</p><p className="mt-1 text-xs text-slate-400">Regras, cálculos e fallback local</p></div><Badge ok texto="Sempre disponível" /></div><p className="mt-5 text-xs leading-5 text-slate-500">Mantém as funções essenciais operando mesmo sem provedor externo.</p></div></div></section>
    <section className="card-ia"><Titulo titulo="Política padrão" descricao="Aplicada a novos clientes e a quem herda a configuração da plataforma." /><div className="mt-5 grid gap-4 lg:grid-cols-4"><Campo label="Provedor"><select value={globalEdit.provedor} onChange={e => { const p = e.target.value as GlobalIA['provedor']; alteraGlobal('provedor', p); alteraGlobal('modelo', modelos[p][0].valor) }} className="input-ia"><option value="automatico">Automático</option><option value="anthropic" disabled={!provedores.anthropic.configurado}>Anthropic {!provedores.anthropic.configurado && '(sem chave)'}</option><option value="openai" disabled={!provedores.openai.configurado}>OpenAI {!provedores.openai.configurado && '(sem chave)'}</option><option value="desativado">Desativado</option></select></Campo><Campo label="Modelo"><select value={globalEdit.modelo} disabled={!['anthropic','openai'].includes(globalEdit.provedor)} onChange={e => alteraGlobal('modelo', e.target.value)} className="input-ia disabled:opacity-50">{modelos[globalEdit.provedor].map(m => <option key={m.valor} value={m.valor}>{m.nome}</option>)}</select></Campo><Campo label="Requisições/mês"><input type="number" min="-1" value={globalEdit.limiteRequisicoes} onChange={e => alteraGlobal('limiteRequisicoes', Number(e.target.value))} className="input-ia" /></Campo><Campo label="Tokens/mês"><input type="number" min="-1" value={globalEdit.limiteTokens} onChange={e => alteraGlobal('limiteTokens', Number(e.target.value))} className="input-ia" /></Campo></div><div className="mt-4 flex items-center justify-between border-t border-slate-800 pt-4"><label className="flex gap-2 text-xs text-slate-300"><input type="checkbox" checked={globalEdit.fallbackAutomatico} onChange={e => alteraGlobal('fallbackAutomatico', e.target.checked)} />Fallback automático em falhas e limites</label><button onClick={salvarGlobal} disabled={salvando || !schemaDisponivel} className="btn-ia">Salvar padrão</button></div></section>
    <section><Titulo titulo="Consumo neste mês" descricao="Telemetria sem armazenar perguntas ou respostas dos clientes." /><div className="mt-3 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Kpi t="Requisições" v={fmt(total.req)} /><Kpi t="Tokens totais" v={fmt(total.tokens)} /><Kpi t="Entrada" v={fmt(total.entrada)} /><Kpi t="Saída" v={fmt(total.saida)} /><Kpi t="Erros" v={fmt(total.erros)} alerta={total.erros > 0} /></div></section>
    <section><div className="flex items-end justify-between"><Titulo titulo="Política por cliente" descricao="Sobrescreva o padrão somente quando necessário." /><input value={busca} onChange={e => setBusca(e.target.value)} placeholder="Buscar empresa..." className="input-ia w-64" /></div><div className="mt-3 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><table className="w-full text-sm"><thead className="bg-slate-800 text-left text-xs text-slate-400"><tr><th className="px-4 py-3">Empresa</th><th>Política</th><th>Uso</th><th>Tokens</th><th>Erros</th><th>Ação</th></tr></thead><tbody className="divide-y divide-slate-800">{filtradas.map(e => <tr key={e.empresaId} className="text-slate-300"><td className="px-4 py-3 font-medium text-white">{e.empresaNome}</td><td><p>{nomes[e.provedor]}</p><p className="text-xs text-slate-500">{e.provedor === 'herdar' ? `${nomes[global.provedor]} · ${global.modelo || 'sem modelo'}` : e.modelo || 'Sem IA generativa'}</p></td><td>{fmt(e.uso.requisicoes)} req.</td><td>{fmt(e.uso.tokens)}</td><td className={e.uso.erros ? 'text-red-400' : 'text-slate-500'}>{e.uso.erros}</td><td><button onClick={() => { setEditando({ ...e }); setMensagem('') }} className="btn-ia">Configurar</button></td></tr>)}</tbody></table></div></section>
    {editando && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="card-ia w-full max-w-xl space-y-5"><div className="flex justify-between"><div><h2 className="font-bold text-white">{editando.empresaNome}</h2><p className="text-xs text-slate-400">Política individual de IA</p></div><button onClick={() => setEditando(null)} className="text-slate-400">✕</button></div><div className="grid gap-4 sm:grid-cols-2"><Campo label="Política"><select value={editando.provedor} onChange={e => { const p = e.target.value as Provedor; alteraEmpresa('provedor', p); alteraEmpresa('modelo', modelos[p][0].valor) }} className="input-ia"><option value="herdar">Herdar padrão</option><option value="automatico">Motor automático</option><option value="anthropic" disabled={!provedores.anthropic.configurado}>Anthropic</option><option value="openai" disabled={!provedores.openai.configurado}>OpenAI</option><option value="desativado">Desativado</option></select></Campo><Campo label="Modelo"><select value={editando.modelo} disabled={!['anthropic','openai'].includes(editando.provedor)} onChange={e => alteraEmpresa('modelo', e.target.value)} className="input-ia disabled:opacity-50">{modelos[editando.provedor].map(m => <option key={m.valor} value={m.valor}>{m.nome}</option>)}</select></Campo><Campo label="Requisições/mês"><input type="number" min="-1" value={editando.limiteRequisicoesMes} onChange={e => alteraEmpresa('limiteRequisicoesMes', Number(e.target.value))} className="input-ia" /></Campo><Campo label="Tokens/mês"><input type="number" min="-1" value={editando.limiteTokensMes} onChange={e => alteraEmpresa('limiteTokensMes', Number(e.target.value))} className="input-ia" /></Campo><label className="col-span-2 flex gap-2 rounded-xl border border-slate-700 p-3 text-xs text-slate-300"><input type="checkbox" checked={editando.fallbackAutomatico} onChange={e => alteraEmpresa('fallbackAutomatico', e.target.checked)} />Fallback automático quando a IA estiver indisponível</label></div>{mensagem && <p className="text-xs text-red-400">{mensagem}</p>}<div className="flex gap-2"><button onClick={() => setEditando(null)} className="flex-1 rounded-xl border border-slate-700 py-2 text-sm text-slate-300">Cancelar</button><button onClick={salvarEmpresa} disabled={salvando || !schemaDisponivel} className="btn-ia flex-1">{salvando ? 'Salvando...' : 'Salvar política'}</button></div></div></div>}
    {mensagem && !editando && <p className="fixed bottom-5 right-5 rounded-xl border border-slate-700 bg-slate-900 px-4 py-3 text-xs text-emerald-400 shadow-xl">{mensagem}</p>}
    <style jsx global>{`.card-ia{border:1px solid #1e293b;background:#0f172a;border-radius:1rem;padding:1.25rem}.input-ia{border-radius:.75rem;border:1px solid #334155;background:#1e293b;padding:.65rem .75rem;color:white;font-size:.8rem}.btn-ia{border-radius:.75rem;background:#4f46e5;padding:.55rem .9rem;color:white;font-size:.75rem;font-weight:600}.btn-ia:disabled{opacity:.4}`}</style>
  </div>
}
function Provider({ nome, detalhe, status }: { nome: string; detalhe: string; status: StatusProvedor }) { return <div className="card-ia"><div className="flex justify-between"><div><p className="font-semibold text-white">{nome}</p><p className="mt-1 text-xs text-slate-400">{detalhe}</p></div><Badge ok={status.configurado} texto={status.configurado ? 'Configurado' : 'Aguardando chave'} /></div><div className="mt-5 rounded-lg bg-slate-950 px-3 py-2 font-mono text-[10px] text-slate-500">{status.origem}</div></div> }
function Badge({ ok, texto }: { ok: boolean; texto: string }) { return <span className={`h-fit rounded-full px-2.5 py-1 text-[10px] font-semibold ${ok ? 'bg-emerald-950 text-emerald-300' : 'bg-amber-950 text-amber-300'}`}>{texto}</span> }
function Kpi({ t, v, alerta }: { t: string; v: string; alerta?: boolean }) { return <div className="card-ia"><p className="text-xs text-slate-400">{t}</p><p className={`mt-1 text-xl font-bold ${alerta ? 'text-red-400' : 'text-white'}`}>{v}</p></div> }
function Titulo({ titulo, descricao }: { titulo: string; descricao: string }) { return <div><h2 className="text-sm font-semibold text-white">{titulo}</h2><p className="mt-1 text-xs text-slate-500">{descricao}</p></div> }
function Campo({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-xs text-slate-400">{label}<div className="mt-1">{children}</div></label> }
